language: node_js
node_js:
  - "0.10.29"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp
  - npm install -g tsd
  - tsd reinstall
after_script:
  - codeclimate < test/coverage/**/lcov.info
script: gulp test 