/// <reference path="typings/node/node.d.ts"/>
var path = require('path');

	// Names
var PACKAGE_NAME = 'ngDecorate',
	ENTRY_FILE_NAME = PACKAGE_NAME + '.ts',
	DTS_FILE_NAME = PACKAGE_NAME + '.d.ts',
	OUT_FILE_NAME = PACKAGE_NAME + '.js',
	TEST_ENTRY_FILE_NAME = PACKAGE_NAME + '.test.ts',
	TEST_OUT_FILE_NAME = ENTRY_FILE_NAME + '.test.js',
	
	// PATHS for library
	SOURCE_FOLDER = path.join(__dirname, 'src'),
	ENTRY_FILE_PATH = path.join(SOURCE_FOLDER, ENTRY_FILE_NAME),
	BUILD_TARGET = path.join(__dirname, 'dev'),
	DTS_TARGET = path.join(BUILD_TARGET, DTS_FILE_NAME),
	TEST_ENTRY_FILE = path.join(__dirname, 'test', TEST_ENTRY_FILE_NAME),
	TEST_TARGET = path.join(BUILD_TARGET),
	TEST_WEBPACK_CONFIG_FILE = path.join(__dirname, 'webpack.test.config.js'),
	
	// PATHS FOR example application
	EXAMPLE_FOLDER = path.join(__dirname, 'example'),
	EXAMPLE_BUILD_TARGET = path.join(EXAMPLE_FOLDER, 'build'),
	EXAMPLE_SOURCE_FOLDER = path.join(EXAMPLE_FOLDER, 'js'),
	EXAMPLE_ENTRY_FILE_PATH = path.join(EXAMPLE_SOURCE_FOLDER, 'app.ts'),
	EXAMPLE_WEBPACK_CONFIG_FILE_PATH = path.join(EXAMPLE_FOLDER, 'webpack.config.js'),
	
	// GLOBS
	DTS_WATCH_TARGET = path.join(SOURCE_FOLDER, '**', '*.ts'),
	BUILD_COPY_SOURCE = path.join(BUILD_TARGET, '**','*');

module.exports = {
	NAMES: {
		PACKAGE_NAME: PACKAGE_NAME,
		ENTRY_FILE_NAME: ENTRY_FILE_NAME,
		OUT_FILE_NAME: OUT_FILE_NAME,
		TEST_OUT_FILE_NAME: TEST_OUT_FILE_NAME
	},
	PATHS: {
		SOURCE_FOLDER : SOURCE_FOLDER,
		ENTRY_FILE_PATH: ENTRY_FILE_PATH,
		BUILD_TARGET: BUILD_TARGET,
		DTS_TARGET: DTS_TARGET,
		EXAMPLE_FOLDER: EXAMPLE_FOLDER,
		EXAMPLE_BUILD_TARGET: EXAMPLE_BUILD_TARGET,
		EXAMPLE_SOURCE_FOLDER: EXAMPLE_SOURCE_FOLDER,
		EXAMPLE_ENTRY_FILE_PATH: EXAMPLE_ENTRY_FILE_PATH,
		EXAMPLE_WEBPACK_CONFIG_FILE_PATH: EXAMPLE_WEBPACK_CONFIG_FILE_PATH,
		TEST_ENTRY_FILE: TEST_ENTRY_FILE,
		TEST_TARGET: TEST_TARGET,
		TEST_WEBPACK_CONFIG_FILE: TEST_WEBPACK_CONFIG_FILE
	},
	
	GLOBS: {
		DTS_WATCH_TARGET: DTS_WATCH_TARGET,
		BUILD_COPY_SOURCE: BUILD_COPY_SOURCE
	},
	
	WATCH: true,
	SERVER: {
		LIVE_RELOAD: true,
		PORT: 3000,
		OPEN: true	
	}
}